[2024-03-12T15:40:39.376+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-03-12T15:38:11.366545+00:00 [queued]>
[2024-03-12T15:40:39.399+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: car_price_prediction.pipeline manual__2024-03-12T15:38:11.366545+00:00 [queued]>
[2024-03-12T15:40:39.400+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-12T15:40:39.426+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): pipeline> on 2024-03-12 15:38:11.366545+00:00
[2024-03-12T15:40:39.437+0000] {standard_task_runner.py:60} INFO - Started process 357 to run task
[2024-03-12T15:40:39.442+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'pipeline', 'manual__2024-03-12T15:38:11.366545+00:00', '--job-id', '1369', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpg6bgpzwm']
[2024-03-12T15:40:39.444+0000] {standard_task_runner.py:88} INFO - Job 1369: Subtask pipeline
[2024-03-12T15:40:39.503+0000] {task_command.py:423} INFO - Running <TaskInstance: car_price_prediction.pipeline manual__2024-03-12T15:38:11.366545+00:00 [running]> on host 02b724958849
[2024-03-12T15:40:39.608+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='car_price_prediction' AIRFLOW_CTX_TASK_ID='pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T15:38:11.366545+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-12T15:38:11.366545+00:00'
[2024-03-12T15:40:41.291+0000] {pipeline.py:117} INFO - model: LogisticRegression, acc_mean: 0.7591, acc_std: 0.0075
[2024-03-12T15:41:27.706+0000] {pipeline.py:117} INFO - model: RandomForestClassifier, acc_mean: 0.7764, acc_std: 0.0022
[2024-03-12T15:42:01.038+0000] {pipeline.py:117} INFO - model: SVC, acc_mean: 0.7871, acc_std: 0.0042
[2024-03-12T15:42:01.040+0000] {pipeline.py:122} INFO - best model: SVC, accuracy: 0.7871
[2024-03-12T15:42:08.898+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/airflow_hw/modules/pipeline.py", line 127, in pipeline
    with open(model_filename, 'wb') as file:
PermissionError: [Errno 13] Permission denied: '/home/airflow/airflow_hw/data/models/cars_pipe_202403121542.pkl'
[2024-03-12T15:42:08.906+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=car_price_prediction, task_id=pipeline, execution_date=20240312T153811, start_date=20240312T154039, end_date=20240312T154208
[2024-03-12T15:42:08.921+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1369 for task pipeline ([Errno 13] Permission denied: '/home/airflow/airflow_hw/data/models/cars_pipe_202403121542.pkl'; 357)
[2024-03-12T15:42:08.953+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-12T15:42:08.976+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
